export const UPDATE_ROUTER_ACCESS_SETTINGS = "UPDATE_ROUTER_ACCESS_SETTINGS";
export const LOAD_VPN_CONNECTIONS = "LOAD_VPN_CONNECTIONS";
export const ADD_VPN_CONNECTION = "ADD_VPN_CONNECTION";
export const DELETE_VPN_CONNECTION = "DELETE_VPN_CONNECTION";
export const UPDATE_VPN_CONNECTION = "UPDATE_VPN_CONNECTION";
